apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: docker.litellm.ai/berriai
      chart: litellm-helm
      targetRevision: 1.83.10-stable 
      helm:
        releaseName: litellm
        valueFiles:
          - $values/apps/litellm/values.yaml
    - repoURL: https://github.com/10Andrea10/openwebui-argocd.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/10Andrea10/openwebui-argocd.git
      targetRevision: main
      path: apps/litellm/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
