apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/10Andrea10/openwebui-argocd.git
    targetRevision: main
    path: apps/nfs/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
