apiVersion: v1
kind: Secret
metadata:
  name: openwebui-db-app
  namespace: cnpg-database
type: kubernetes.io/basic-auth
stringData:
  username: openwebui
  password: ciaociaociao
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-db-app
  namespace: cnpg-database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: litellm
  password: ciaolitellm
