apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.openwebui.com/
    chart: open-webui
    targetRevision: 14.2.0
    # https://artifacthub.io/packages/helm/open-webui/open-webui
    helm:
      releaseName: open-webui
      valuesObject:
        replicaCount: 1
        image:
          tag: "v0.9.2"
        persistence:
          enabled: true
          existingClaim: openwebui-nfs-pvc
          accessModes:
            - ReadWriteMany
        ingress:
          enabled: false
        ollama:
          enabled: false
        service:
          type: NodePort
          port: 80
          nodePort: 30880
        extraEnvVars:
          - name: WEBUI_SECRET_KEY
            value: "random_secret_for_token_generation"
          - name: ENABLE_SIGNUP
            value: "true"
        databaseUrl: "postgresql://openwebui:ciaociaociao@postgres-cluster-rw.cnpg-database.svc:5432/openwebui?sslmode=disable"
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
