apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
